### ISSUE TITLE
IE: Org Form: User can't reorder video items

### ISSUE THREAD

**Issue by lsweltz** [InterActionNGO/NGO-admin#27]
URL: http://office.ngoaidmap.staging.vigetx.com/admin/organizations/124/media_resources
OS: Windows 10
Browser: IE 11
- Reorder arrows appear on top of video but user can't click the arrows
- Images work fine
- [Screenshot](https://www.dropbox.com/s/kqkw75pn7y4bj55/Screenshot%202016-09-26%2015.41.42.png?dl=0)

**Comment by mzlock** [comment]
This could be a front-end or a back-end thing.  Will investigate.

**Comment by mzlock** [comment]
Looks like this is a IE issue where hovering over an iframe (the video) is not triggering the hover state correctly.  Fixed by moving the controls down, partially off the video.

![screen shot 2016-10-07 at 5 06 01 pm](https://cloud.githubusercontent.com/assets/1087001/19205488/cb5d95e4-8cb0-11e6-8dcb-3f31a49d4b5c.png)

**Comment by brianjlandau** [comment]
@mzlock @lsweltz what's the status on this? Can we close it?

**Comment by lsweltz** [comment]
👍
