### ISSUE TITLE
Project Form: Update Partner Field

### ISSUE THREAD

**Issue by lsweltz** [InterActionNGO/NGO-admin#6]
On the project form:

- Replace the plain text Partners field with a drop-down field that displays all existing partners (international and local).

**Comment by RBFraxinus** [comment]
Clarification:   in the project form, a user wanting to add a partner to a project should have all organizations to choose from (the entire org table records), not just those that have been recorded as partners previously.  Therefore the dropdown should list all organizations in the table, regardless of existing role relations.

That's a lot of organizations...which is why we really want the input filter where the user can start typing and filter the list by finding those org names that contain the input value.

**Comment by mzlock** [comment]
@RBFraxinus - I was able to create the field as an autocomplete multi-select field, so we can keep the auto-select and be able to select multiple partners.  @brianjlandau should be able to take it from here and fill in all of the organizations as options.

**Comment by RBFraxinus** [comment]
@mzlock sounds good
